# Generated by Django 5.2.6 on 2025-09-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(help_text='Exemple: Carburant, Huile, Réparation...', max_length=100)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantité (litres) si applicable', max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant en FCFA', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
